name: bubble_showcase
description: BubbleShowcase is a small but powerful flutter package that allows you to highlight specific parts of your app to explain them to the user or to show your app new features.
version: 1.1.0
homepage: https://github.com/Skyost/BubbleShowcase

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: '>=2.0.0 <3.0.0'

dev_dependencies: 
  flutter_lints: '>=1.0.4'
